In [8]:
#Libraries
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

In [9]:
#ignore the warnings
import warnings
warnings.filterwarnings("ignore")

In [10]:
#call the variables
df = pd.read_csv('online.csv')
df

,Unnamed: 0,order_status,Monthly Income,latitude,Marital Status,Gender,employment_status,Family size,Reviews,Pin code,Age,longitude,Educational Qualifications,Unnamed: 13,9,#@%
0,0,Yes,25001 to 50000,13.0262,Married,Male,Employee,5.0,Positive,560045,28.0,77.6200,Post Graduate,Yes,NaN,swiggyscount
1,1,Yes,No Income,12.9770,Single,Male,Student,NaN,Positive,560009,NaN,77.5773,Post Graduate,Yes,NaN,*7435
2,2,Yes,No Income,12.9770,Single,Female,Student,NaN,Positive,560009,NaN,77.5773,Post Graduate,Yes,NaN,*7435
3,3,Yes,No Income,13.0019,Single,Female,Student,NaN,Positive,560003,NaN,77.5713,Post Graduate,Yes,NaN,*7435
4,4,Yes,More than 50000,13.0626,Married,Male,Self Employeed,NaN,Positive,560015,NaN,77.5284,School,Yes,NaN,*7435
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,383,Yes,No Income,12.9883,Single,Female,Student,5.0,Positive,560051,24.0,77.5987,Post Graduate,Yes,NaN,NaN
384,384,Yes,No Income,13.0223,Single,Male,Student,3.0,Positive,560049,23.0,77.7132,Graduate,Yes,NaN,NaN
385,385,Yes,10001 to 25000,12.9850,Single,Female,Student,5.0,Positive,560010,22.0,77.5533,Post Graduate,Yes,NaN,NaN
386,386,Yes,10001 to 25000,12.9698,Single,Female,Employee,3.0,Positive,560066,22.0,77.7500,Graduate,Yes,NaN,NaN
387,387,Yes,No Income,12.9770,Single,Male,Student,1.0,Positive,560009,25.0,77.5773,Graduate,Yes,NaN,NaN

In [12]:
#Show Top 5 records
df.head()

,Unnamed: 0,order_status,Monthly Income,latitude,Marital Status,Gender,employment_status,Family size,Reviews,Pin code,Age,longitude,Educational Qualifications,Unnamed: 13,9,#@%
0,0,Yes,25001 to 50000,13.0262,Married,Male,Employee,5.0,Positive,560045,28.0,77.6200,Post Graduate,Yes,NaN,swiggyscount
1,1,Yes,No Income,12.9770,Single,Male,Student,NaN,Positive,560009,NaN,77.5773,Post Graduate,Yes,NaN,*7435
2,2,Yes,No Income,12.9770,Single,Female,Student,NaN,Positive,560009,NaN,77.5773,Post Graduate,Yes,NaN,*7435
3,3,Yes,No Income,13.0019,Single,Female,Student,NaN,Positive,560003,NaN,77.5713,Post Graduate,Yes,NaN,*7435
4,4,Yes,More than 50000,13.0626,Married,Male,Self Employeed,NaN,Positive,560015,NaN,77.5284,School,Yes,NaN,*7435

In [7]:
#Show bottom 10 records
df.tail(10)

,Unnamed: 0,order_status,Monthly Income,latitude,Marital Status,Gender,employment_status,Family size,Reviews,Pin code,Age,longitude,Educational Qualifications,Unnamed: 13,9,#@%
378,378,No,10001 to 25000,12.9706,Married,Female,Self Employeed,5.0,Negative,560075,26.0,77.6529,Graduate,No,NaN,NaN
379,379,Yes,No Income,12.8845,Single,Male,Student,2.0,Positive,560076,23.0,77.6036,Post Graduate,Yes,NaN,NaN
380,380,Yes,25001 to 50000,12.9766,Single,Male,Self Employeed,3.0,Positive,560001,26.0,77.5993,Graduate,Yes,NaN,NaN
381,381,No,More than 50000,13.0503,Single,Male,Employee,4.0,Positive,560013,27.0,77.5529,Ph.D,No,NaN,NaN
382,382,No,More than 50000,12.9337,Single,Male,Employee,3.0,Negative,560011,26.0,77.5900,Post Graduate,No,NaN,NaN
383,383,Yes,No Income,12.9883,Single,Female,Student,5.0,Positive,560051,24.0,77.5987,Post Graduate,Yes,NaN,NaN
384,384,Yes,No Income,13.0223,Single,Male,Student,3.0,Positive,560049,23.0,77.7132,Graduate,Yes,NaN,NaN
385,385,Yes,10001 to 25000,12.9850,Single,Female,Student,5.0,Positive,560010,22.0,77.5533,Post Graduate,Yes,NaN,NaN
386,386,Yes,10001 to 25000,12.9698,Single,Female,Employee,3.0,Positive,560066,22.0,77.7500,Graduate,Yes,NaN,NaN
387,387,Yes,No Income,12.9770,Single,Male,Student,1.0,Positive,560009,25.0,77.5773,Graduate,Yes,NaN,NaN

In [11]:
#Select a specific column
df['Gender']

0        Male
1        Male
2      Female
3      Female
4        Male
        ...
383    Female
384      Male
385    Female
386    Female
387      Male
Name: Gender, Length: 388, dtype: object

In [9]:
#Select a speciic column alt
df.Gender

0        Male
1        Male
2      Female
3      Female
4        Male
        ...
383    Female
384      Male
385    Female
386    Female
387      Male
Name: Gender, Length: 388, dtype: object

In [13]:
#filter record for Gender = Female
df[df['Gender'] == 'Female']

,Unnamed: 0,order_status,Monthly Income,latitude,Marital Status,Gender,employment_status,Family size,Reviews,Pin code,Age,longitude,Educational Qualifications,Unnamed: 13,9,#@%
2,2,Yes,No Income,12.9770,Single,Female,Student,NaN,Positive,560009,NaN,77.5773,Post Graduate,Yes,NaN,*7435
3,3,Yes,No Income,13.0019,Single,Female,Student,NaN,Positive,560003,NaN,77.5713,Post Graduate,Yes,NaN,*7435
5,5,Yes,No Income,12.9369,Single,Female,Student,2.0,Positive,560095,22.0,77.6407,Graduate,Yes,NaN,*7435
7,7,No,25001 to 50000,13.0103,Single,Female,Self Employeed,3.0,Negative,560080,24.0,77.5796,Post Graduate,No,NaN,NaN
10,10,Yes,More than 50000,12.9299,Married,Female,Employee,2.0,Positive,560103,27.0,77.6848,Post Graduate,Yes,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377,377,No,25001 to 50000,12.9783,Married,Female,Employee,4.0,Negative,560038,29.0,77.6408,Graduate,No,NaN,NaN
378,378,No,10001 to 25000,12.9706,Married,Female,Self Employeed,5.0,Negative,560075,26.0,77.6529,Graduate,No,NaN,NaN
383,383,Yes,No Income,12.9883,Single,Female,Student,5.0,Positive,560051,24.0,77.5987,Post Graduate,Yes,NaN,NaN
385,385,Yes,10001 to 25000,12.9850,Single,Female,Student,5.0,Positive,560010,22.0,77.5533,Post Graduate,Yes,NaN,NaN
386,386,Yes,10001 to 25000,12.9698,Single,Female,Employee,3.0,Positive,560066,22.0,77.7500,Graduate,Yes,NaN,NaN

In [15]:
#filter record for Gender = Male
df[df['Gender'] == 'Male']

,Unnamed: 0,order_status,Monthly Income,latitude,Marital Status,Gender,employment_status,Family size,Reviews,Pin code,Age,longitude,Educational Qualifications,Unnamed: 13,9,#@%
0,0,Yes,25001 to 50000,13.0262,Married,Male,Employee,5.0,Positive,560045,28.0,77.6200,Post Graduate,Yes,NaN,swiggyscount
1,1,Yes,No Income,12.9770,Single,Male,Student,NaN,Positive,560009,NaN,77.5773,Post Graduate,Yes,NaN,*7435
4,4,Yes,More than 50000,13.0626,Married,Male,Self Employeed,NaN,Positive,560015,NaN,77.5284,School,Yes,NaN,*7435
6,6,Yes,More than 50000,12.9442,Married,Male,Employee,6.0,Positive,560030,25.0,77.6076,Post Graduate,Yes,NaN,NaN
8,8,Yes,10001 to 25000,12.9820,Married,Male,Self Employeed,3.0,Negative,560008,22.0,77.6256,School,Yes,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380,380,Yes,25001 to 50000,12.9766,Single,Male,Self Employeed,3.0,Positive,560001,26.0,77.5993,Graduate,Yes,NaN,NaN
381,381,No,More than 50000,13.0503,Single,Male,Employee,4.0,Positive,560013,27.0,77.5529,Ph.D,No,NaN,NaN
382,382,No,More than 50000,12.9337,Single,Male,Employee,3.0,Negative,560011,26.0,77.5900,Post Graduate,No,NaN,NaN
384,384,Yes,No Income,13.0223,Single,Male,Student,3.0,Positive,560049,23.0,77.7132,Graduate,Yes,NaN,NaN
387,387,Yes,No Income,12.9770,Single,Male,Student,1.0,Positive,560009,25.0,77.5773,Graduate,Yes,NaN,NaN

In [12]:
#show employment when self employeed
df[df['employment_status'] == 'Self Employeed']

,Unnamed: 0,order_status,Monthly Income,latitude,Marital Status,Gender,employment_status,Family size,Reviews,Pin code,Age,longitude,Educational Qualifications,Unnamed: 13,9,#@%
4,4,Yes,More than 50000,13.0626,Married,Male,Self Employeed,NaN,Positive,560015,NaN,77.5284,School,Yes,NaN,*7435
7,7,No,25001 to 50000,13.0103,Single,Female,Self Employeed,3.0,Negative,560080,24.0,77.5796,Post Graduate,No,NaN,NaN
8,8,Yes,10001 to 25000,12.9820,Married,Male,Self Employeed,3.0,Negative,560008,22.0,77.6256,School,Yes,NaN,NaN
20,20,No,More than 50000,13.0809,Married,Male,Self Employeed,1.0,Negative,560097,30.0,77.5565,Graduate,No,NaN,NaN
21,21,No,10001 to 25000,12.9706,Married,Female,Self Employeed,5.0,Negative,560075,26.0,77.6529,Graduate,No,NaN,NaN
22,22,Yes,10001 to 25000,12.9438,Single,Female,Self Employeed,5.0,Positive,560004,23.0,77.5738,Post Graduate,Yes,NaN,NaN
26,26,Yes,10001 to 25000,12.9820,Married,Male,Self Employeed,3.0,Negative,560008,32.0,77.6256,School,Yes,NaN,NaN
34,34,Yes,10001 to 25000,13.0206,Single,Male,Self Employeed,3.0,Positive,560043,25.0,77.6479,Graduate,Yes,NaN,NaN
49,49,No,25001 to 50000,12.9217,Married,Male,Self Employeed,6.0,Negative,560041,27.0,77.5936,Graduate,No,NaN,NaN
60,60,Yes,25001 to 50000,13.0078,Married,Female,Self Employeed,3.0,Positive,560055,27.0,77.5577,Graduate,Yes,NaN,NaN
63,63,Yes,More than 50000,12.8845,Single,Male,Self Employeed,6.0,Positive,560076,29.0,77.6036,Graduate,Yes,NaN,NaN
72,72,No,More than 50000,12.9570,Married,Male,Self Employeed,3.0,Negative,560018,26.0,77.5637,Post Graduate,No,NaN,NaN
78,78,Yes,More than 50000,13.0206,Married,Male,Self Employeed,4.0,Positive,560043,25.0,77.6479,Post Graduate,Yes,NaN,NaN
81,81,Yes,25001 to 50000,12.9561,Married,Male,Self Employeed,3.0,Positive,560027,25.0,77.5921,Graduate,Yes,NaN,NaN
85,85,Yes,More than 50000,13.0103,Prefer not to say,Male,Self Employeed,2.0,Positive,560080,26.0,77.5796,Post Graduate,Yes,NaN,NaN
92,92,Yes,More than 50000,12.9859,Single,Male,Self Employeed,3.0,Positive,560093,25.0,77.6713,School,Yes,NaN,NaN
95,95,Yes,10001 to 25000,13.0206,Single,Male,Self Employeed,3.0,Positive,560043,25.0,77.6479,Graduate,Yes,NaN,NaN
105,105,Yes,More than 50000,13.0487,Married,Male,Self Employeed,6.0,Positive,560024,31.0,77.5923,School,Yes,NaN,NaN
106,106,Yes,25001 to 50000,12.9635,Married,Female,Self Employeed,3.0,Positive,560002,27.0,77.5821,Graduate,Yes,NaN,NaN
110,110,Yes,10001 to 25000,12.9149,Single,Male,Self Employeed,2.0,Positive,560070,28.0,77.5635,Post Graduate,Yes,NaN,NaN
114,114,No,25001 to 50000,12.9251,Married,Male,Self Employeed,6.0,Negative,560059,30.0,77.4992,School,No,NaN,NaN
116,116,No,25001 to 50000,13.0103,Single,Female,Self Employeed,3.0,Negative,560080,24.0,77.5796,Post Graduate,No,NaN,NaN
145,145,No,More than 50000,12.9635,Married,Male,Self Employeed,6.0,Negative,560002,24.0,77.5821,Ph.D,No,NaN,NaN
155,155,Yes,More than 50000,12.9783,Single,Male,Self Employeed,2.0,Positive,560038,25.0,77.6408,Graduate,Yes,NaN,NaN
158,158,No,10001 to 25000,12.9698,Single,Male,Self Employeed,1.0,Positive,560066,26.0,77.7500,Ph.D,No,NaN,NaN
161,161,No,25001 to 50000,12.9570,Married,Female,Self Employeed,3.0,Positive,560018,25.0,77.5637,Post Graduate,No,NaN,NaN
162,162,Yes,More than 50000,12.9859,Single,Male,Self Employeed,3.0,Positive,560093,25.0,77.6713,School,Yes,NaN,NaN
186,186,Yes,10001 to 25000,12.9579,Married,Female,Self Employeed,5.0,Positive,560007,24.0,77.6309,Graduate,Yes,NaN,NaN
212,212,No,More than 50000,13.0809,Married,Male,Self Employeed,1.0,Negative,560097,30.0,77.5565,Graduate,No,NaN,NaN
216,216,No,25001 to 50000,12.9217,Married,Male,Self Employeed,6.0,Positive,560041,27.0,77.5936,Graduate,No,NaN,NaN
217,217,No,25001 to 50000,12.9217,Married,Male,Self Employeed,6.0,Positive,560041,27.0,77.5936,Graduate,No,NaN,NaN
236,236,No,More than 50000,13.0734,Married,Female,Self Employeed,6.0,Positive,560014,27.0,77.5464,Graduate,No,NaN,NaN
251,251,Yes,25001 to 50000,12.9980,Single,Male,Self Employeed,3.0,Positive,560005,25.0,77.6227,Graduate,Yes,NaN,NaN
259,259,Yes,More than 50000,12.9783,Single,Male,Self Employeed,2.0,Positive,560038,25.0,77.6408,Graduate,Yes,NaN,NaN
262,262,Yes,More than 50000,13.0103,Prefer not to say,Male,Self Employeed,2.0,Positive,560080,26.0,77.5796,Post Graduate,Yes,NaN,NaN
273,273,Yes,More than 50000,12.9967,Married,Male,Self Employeed,6.0,Positive,560067,30.0,77.7582,Graduate,Yes,NaN,NaN
278,278,Yes,10001 to 25000,13.0206,Single,Male,Self Employeed,3.0,Positive,560043,25.0,77.6479,Graduate,Yes,NaN,NaN
279,279,No,More than 50000,13.0138,Prefer not to say,Male,Self Employeed,2.0,Positive,560006,24.0,77.5877,Ph.D,No,NaN,NaN
289,289,No,25001 to 50000,13.0103,Single,Female,Self Employeed,3.0,Negative,560080,24.0,77.5796,Post Graduate,No,NaN,NaN
300,300,Yes,More than 50000,12.9343,Married,Female,Self Employeed,2.0,Positive,560029,24.0,77.6044,Graduate,Yes,NaN,NaN
304,304,Yes,25001 to 50000,12.9635,Single,Female,Self Employeed,3.0,Positive,560002,26.0,77.5821,Post Graduate,Yes,NaN,NaN
306,306,No,10001 to 25000,12.9706,Married,Female,Self Employeed,5.0,Negative,560075,26.0,77.6529,Graduate,No,NaN,NaN
317,317,Yes,More than 50000,13.0103,Prefer not to say,Male,Self Employeed,2.0,Positive,560080,26.0,77.5796,Post Graduate,Yes,NaN,NaN
322,322,Yes,More than 50000,12.9890,Married,Male,Self Employeed,3.0,Positive,560079,27.0,77.5332,Graduate,Yes,NaN,NaN
328,328,Yes,More than 50000,12.8845,Single,Male,Self Employeed,6.0,Positive,560076,29.0,77.6036,Graduate,Yes,NaN,NaN
335,335,Yes,10001 to 25000,12.9261,Married,Female,Self Employeed,2.0,Positive,560034,27.0,77.6221,Post Graduate,Yes,NaN,NaN
341,341,Yes,10001 to 25000,12.9149,Single,Male,Self Employeed,2.0,Positive,560070,28.0,77.5635,Post Graduate,Yes,NaN,NaN
344,344,No,10001 to 25000,13.0289,Married,Male,Self Employeed,2.0,Negative,560022,28.0,77.5400,Graduate,No,NaN,NaN
345,345,Yes,More than 50000,12.8845,Single,Male,Self Employeed,6.0,Positive,560076,29.0,77.6036,Graduate,Yes,NaN,NaN
349,349,Yes,More than 50000,12.9662,Married,Male,Self Employeed,4.0,Negative,560025,30.0,77.6068,Uneducated,Yes,NaN,NaN
361,361,No,More than 50000,12.9766,Married,Female,Self Employeed,5.0,Positive,560001,27.0,77.5993,Graduate,No,NaN,NaN
376,376,Yes,More than 50000,12.9783,Single,Male,Self Employeed,2.0,Positive,560038,25.0,77.6408,Graduate,Yes,NaN,NaN
378,378,No,10001 to 25000,12.9706,Married,Female,Self Employeed,5.0,Negative,560075,26.0,77.6529,Graduate,No,NaN,NaN
380,380,Yes,25001 to 50000,12.9766,Single,Male,Self Employeed,3.0,Positive,560001,26.0,77.5993,Graduate,Yes,NaN,NaN

In [16]:
#show marital status when single
df[df['Marital Status'] == 'Single']

,Unnamed: 0,order_status,Monthly Income,latitude,Marital Status,Gender,employment_status,Family size,Reviews,Pin code,Age,longitude,Educational Qualifications,Unnamed: 13,9,#@%
1,1,Yes,No Income,12.9770,Single,Male,Student,NaN,Positive,560009,NaN,77.5773,Post Graduate,Yes,NaN,*7435
2,2,Yes,No Income,12.9770,Single,Female,Student,NaN,Positive,560009,NaN,77.5773,Post Graduate,Yes,NaN,*7435
3,3,Yes,No Income,13.0019,Single,Female,Student,NaN,Positive,560003,NaN,77.5713,Post Graduate,Yes,NaN,*7435
5,5,Yes,No Income,12.9369,Single,Female,Student,2.0,Positive,560095,22.0,77.6407,Graduate,Yes,NaN,*7435
7,7,No,25001 to 50000,13.0103,Single,Female,Self Employeed,3.0,Negative,560080,24.0,77.5796,Post Graduate,No,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,383,Yes,No Income,12.9883,Single,Female,Student,5.0,Positive,560051,24.0,77.5987,Post Graduate,Yes,NaN,NaN
384,384,Yes,No Income,13.0223,Single,Male,Student,3.0,Positive,560049,23.0,77.7132,Graduate,Yes,NaN,NaN
385,385,Yes,10001 to 25000,12.9850,Single,Female,Student,5.0,Positive,560010,22.0,77.5533,Post Graduate,Yes,NaN,NaN
386,386,Yes,10001 to 25000,12.9698,Single,Female,Employee,3.0,Positive,560066,22.0,77.7500,Graduate,Yes,NaN,NaN
387,387,Yes,No Income,12.9770,Single,Male,Student,1.0,Positive,560009,25.0,77.5773,Graduate,Yes,NaN,NaN

In [18]:
#show marital status and gender where single and female
MaritalStatusandGender=df[(df['Marital Status'] == 'Single') & (df['Gender'] == 'Female')]
MaritalStatusandGender

,Unnamed: 0,order_status,Monthly Income,latitude,Marital Status,Gender,employment_status,Family size,Reviews,Pin code,Age,longitude,Educational Qualifications,Unnamed: 13,9,#@%
2,2,Yes,No Income,12.9770,Single,Female,Student,NaN,Positive,560009,NaN,77.5773,Post Graduate,Yes,NaN,*7435
3,3,Yes,No Income,13.0019,Single,Female,Student,NaN,Positive,560003,NaN,77.5713,Post Graduate,Yes,NaN,*7435
5,5,Yes,No Income,12.9369,Single,Female,Student,2.0,Positive,560095,22.0,77.6407,Graduate,Yes,NaN,*7435
7,7,No,25001 to 50000,13.0103,Single,Female,Self Employeed,3.0,Negative,560080,24.0,77.5796,Post Graduate,No,NaN,NaN
17,17,Yes,No Income,12.9343,Single,Female,Student,3.0,Positive,560029,22.0,77.6044,Graduate,Yes,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
364,364,Yes,No Income,13.0487,Single,Female,Student,4.0,Positive,560024,23.0,77.5923,Post Graduate,Yes,NaN,NaN
373,373,Yes,No Income,12.9119,Single,Female,Student,2.0,Positive,560102,22.0,77.6446,Post Graduate,Yes,NaN,NaN
383,383,Yes,No Income,12.9883,Single,Female,Student,5.0,Positive,560051,24.0,77.5987,Post Graduate,Yes,NaN,NaN
385,385,Yes,10001 to 25000,12.9850,Single,Female,Student,5.0,Positive,560010,22.0,77.5533,Post Graduate,Yes,NaN,NaN
386,386,Yes,10001 to 25000,12.9698,Single,Female,Employee,3.0,Positive,560066,22.0,77.7500,Graduate,Yes,NaN,NaN

In [19]:
#How to check for null
df.isna().sum()

Unnamed: 0                      0
order_status                    0
Monthly Income                  0
latitude                        0
Marital Status                  0
Gender                          0
employment_status               0
Family size                    19
Reviews                         0
Pin code                        0
Age                            19
longitude                       0
Educational Qualifications      0
Unnamed: 13                     0
9                             388
#@%                           382
dtype: int64

In [21]:
#How to drop null in Family size
df=df.dropna(subset = ['Family size'])
df

,Unnamed: 0,order_status,Monthly Income,latitude,Marital Status,Gender,employment_status,Family size,Reviews,Pin code,Age,longitude,Educational Qualifications,Unnamed: 13,9,#@%
0,0,Yes,25001 to 50000,13.0262,Married,Male,Employee,5.0,Positive,560045,28.0,77.6200,Post Graduate,Yes,NaN,swiggyscount
5,5,Yes,No Income,12.9369,Single,Female,Student,2.0,Positive,560095,22.0,77.6407,Graduate,Yes,NaN,*7435
6,6,Yes,More than 50000,12.9442,Married,Male,Employee,6.0,Positive,560030,25.0,77.6076,Post Graduate,Yes,NaN,NaN
7,7,No,25001 to 50000,13.0103,Single,Female,Self Employeed,3.0,Negative,560080,24.0,77.5796,Post Graduate,No,NaN,NaN
8,8,Yes,10001 to 25000,12.9820,Married,Male,Self Employeed,3.0,Negative,560008,22.0,77.6256,School,Yes,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,383,Yes,No Income,12.9883,Single,Female,Student,5.0,Positive,560051,24.0,77.5987,Post Graduate,Yes,NaN,NaN
384,384,Yes,No Income,13.0223,Single,Male,Student,3.0,Positive,560049,23.0,77.7132,Graduate,Yes,NaN,NaN
385,385,Yes,10001 to 25000,12.9850,Single,Female,Student,5.0,Positive,560010,22.0,77.5533,Post Graduate,Yes,NaN,NaN
386,386,Yes,10001 to 25000,12.9698,Single,Female,Employee,3.0,Positive,560066,22.0,77.7500,Graduate,Yes,NaN,NaN
387,387,Yes,No Income,12.9770,Single,Male,Student,1.0,Positive,560009,25.0,77.5773,Graduate,Yes,NaN,NaN

In [22]:
#How to check for null to confirm
df.isna().sum()

Unnamed: 0                      0
order_status                    0
Monthly Income                  0
latitude                        0
Marital Status                  0
Gender                          0
employment_status               0
Family size                     0
Reviews                         0
Pin code                        0
Age                             0
longitude                       0
Educational Qualifications      0
Unnamed: 13                     0
9                             369
#@%                           367
dtype: int64

In [23]:
#See all the columns
df=pd.DataFrame(df)
df.head()
columnlist=list(df.columns)
columnlist

['Unnamed: 0',
 'order_status',
 'Monthly Income',
 'latitude',
 'Marital Status',
 'Gender',
 'employment_status',
 'Family size',
 'Reviews',
 'Pin code',
 'Age',
 'longitude',
 'Educational Qualifications',
 'Unnamed: 13',
 '9',
 '#@%']

In [17]:
#How to drop column
df.drop(columns = '#@%' ,inplace = True)
df.head()

,Unnamed: 0,order_status,Monthly Income,latitude,Marital Status,Gender,employment_status,Family size,Reviews,Pin code,Age,longitude,Educational Qualifications,Unnamed: 13,9
0,0,Yes,25001 to 50000,13.0262,Married,Male,Employee,5.0,Positive,560045,28.0,77.6200,Post Graduate,Yes,NaN
1,1,Yes,No Income,12.9770,Single,Male,Student,NaN,Positive,560009,NaN,77.5773,Post Graduate,Yes,NaN
2,2,Yes,No Income,12.9770,Single,Female,Student,NaN,Positive,560009,NaN,77.5773,Post Graduate,Yes,NaN
3,3,Yes,No Income,13.0019,Single,Female,Student,NaN,Positive,560003,NaN,77.5713,Post Graduate,Yes,NaN
4,4,Yes,More than 50000,13.0626,Married,Male,Self Employeed,NaN,Positive,560015,NaN,77.5284,School,Yes,NaN

In [18]:
#How to check for null to confirm
df.isna().sum()

Unnamed: 0                      0
order_status                    0
Monthly Income                  0
latitude                        0
Marital Status                  0
Gender                          0
employment_status               0
Family size                    19
Reviews                         0
Pin code                        0
Age                            19
longitude                       0
Educational Qualifications      0
Unnamed: 13                     0
9                             388
dtype: int64

In [21]:
#How to read other files
pd.read_csv('C:\\Users\\WORK-PC\\Documents\\ETL Training\\Inbound\\Report\\online.csv')

,Unnamed: 0,order_status,Monthly Income,latitude,Marital Status,Gender,employment_status,Family size,Reviews,Pin code,Age,longitude,Educational Qualifications,Unnamed: 13,9,#@%
0,0,Yes,25001 to 50000,13.0262,Married,Male,Employee,5.0,Positive,560045,28.0,77.6200,Post Graduate,Yes,NaN,swiggyscount
1,1,Yes,No Income,12.9770,Single,Male,Student,NaN,Positive,560009,NaN,77.5773,Post Graduate,Yes,NaN,*7435
2,2,Yes,No Income,12.9770,Single,Female,Student,NaN,Positive,560009,NaN,77.5773,Post Graduate,Yes,NaN,*7435
3,3,Yes,No Income,13.0019,Single,Female,Student,NaN,Positive,560003,NaN,77.5713,Post Graduate,Yes,NaN,*7435
4,4,Yes,More than 50000,13.0626,Married,Male,Self Employeed,NaN,Positive,560015,NaN,77.5284,School,Yes,NaN,*7435
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,383,Yes,No Income,12.9883,Single,Female,Student,5.0,Positive,560051,24.0,77.5987,Post Graduate,Yes,NaN,NaN
384,384,Yes,No Income,13.0223,Single,Male,Student,3.0,Positive,560049,23.0,77.7132,Graduate,Yes,NaN,NaN
385,385,Yes,10001 to 25000,12.9850,Single,Female,Student,5.0,Positive,560010,22.0,77.5533,Post Graduate,Yes,NaN,NaN
386,386,Yes,10001 to 25000,12.9698,Single,Female,Employee,3.0,Positive,560066,22.0,77.7500,Graduate,Yes,NaN,NaN
387,387,Yes,No Income,12.9770,Single,Male,Student,1.0,Positive,560009,25.0,77.5773,Graduate,Yes,NaN,NaN

In [ ]:
# clean, Load, read data into sql server ref wk 16 xtraclass ending